### ISSUE TITLE
calling to_json on notifiable model

### ISSUE THREAD

**Issue by OrrYakobi** [simukappu/activity_notification#115]
When calling to_json on a notifiable model, the following error occurs:

```
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>MODEL}, missing required keys: [:id]
```

Here is the backtrace
```
/.rvm/gems/ruby-2.5.7/gems/actionpack-5.1.7/lib/action_dispatch/journey/formatter.rb:55:in `generate'
/.rvm/gems/ruby-2.5.7/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:748:in `generate'
/.rvm/gems/ruby-2.5.7/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:779:in `generate'
/.rvm/gems/ruby-2.5.7/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:826:in `url_for'
/.rvm/gems/ruby-2.5.7/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:277:in `call'
/.rvm/gems/ruby-2.5.7/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:218:in `call'
/.rvm/gems/ruby-2.5.7/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:335:in `block (2 levels) in define_url_helper'
/.rvm/gems/ruby-2.5.7/gems/activemodel-5.1.7/lib/active_model/serialization.rb:135:in `block in serializable_hash'
/.rvm/gems/ruby-2.5.7/gems/activemodel-5.1.7/lib/active_model/serialization.rb:135:in `each'
/.rvm/gems/ruby-2.5.7/gems/activemodel-5.1.7/lib/active_model/serialization.rb:135:in `serializable_hash'
/.rvm/gems/ruby-2.5.7/gems/activerecord-5.1.7/lib/active_record/serialization.rb:17:in `serializable_hash'
/.rvm/gems/ruby-2.5.7/gems/activemodel-5.1.7/lib/active_model/serializers/json.rb:99:in `as_json'
/.rvm/gems/ruby-2.5.7/gems/activesupport-5.1.7/lib/active_support/json/encoding.rb:33:in `encode'
/.rvm/gems/ruby-2.5.7/gems/activesupport-5.1.7/lib/active_support/json/encoding.rb:20:in `encode'
/.rvm/gems/ruby-2.5.7/gems/activesupport-5.1.7/lib/active_support/core_ext/object/json.rb:39:in `to_json'
(pry):2:in `__pry__'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `eval'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `evaluate_ruby'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:355:in `handle_line'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in eval'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/repl.rb:77:in `block in repl'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/.rvm/gems/ruby-2.5.7/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/.rvm/gems/ruby-2.5.7/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:62:in `start'
/.rvm/gems/ruby-2.5.7/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:17:in `start'
/.rvm/gems/ruby-2.5.7/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:97:in `perform'
/.rvm/gems/ruby-2.5.7/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/.rvm/gems/ruby-2.5.7/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/.rvm/gems/ruby-2.5.7/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/.rvm/gems/ruby-2.5.7/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
/.rvm/gems/ruby-2.5.7/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
/.rvm/gems/ruby-2.5.7/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by simukappu** [comment]
No activity_notification code is found in your backtrace. Notifiable model is your own model in your Rails application. Why do you think it is a gem's issue?

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.

**Comment by sjieg** [comment]
@simukappu I see the same issue. I don't have much of a backtrace, but basically my model with:
```
  acts_as_notifiable :users,
                     targets: ->(profile, key) {
                       notification_targets(profile, key)
                     },
                     printable_notifiable_name: ->(profile) { "a report update in #{profile.name}" },
                     notifiable_path: :profile_notifiable_path,
                     email_allowed: true
```
Generates an error when doing `MyModel.all.first(10).to_json`:
```
No route matches {:action=>"show", :controller=>"profiles"}, missing required keys: [:id]
```
And it does not when I comment out the `act_as_notifiable` code.

Seems like the `acts_as_notifiable` functions are called while generating the JSON structure, but without passing along the id's.

**Comment by sjieg** [comment]
Hello! I did further research. The above is not the issue, but I do believe `activity_notification` is causing it.

1. Create a model with a column that is `mymodel_url`.
2. Make the model `acts_as_notifiable`
3. Populate with data
3. Call `Mymodel.all.first(10).to_json`

Actual: No route matches {:action=>"show", :controller=>"mymodel"}, missing required keys: [:id]
Expected: The model to be converted to json

----

I've seen this same issue as well calling other functions while we still had the `:profile_url` column present. Luckely this was legacy code, and we could just remove the column without problems.

*workaround*

```
Mymodel.all.first(10).to_json(except: :mymodel_url)
```

@simukappu if I would need to make a guess, I think something in the `activity_notification` gem is trying to execute every model attribute, causing `:mymodel_url` to be executed as `mymodel_url()`, triggering the `ActionController` expecting an `:id` for that attribute.

Very edge case, but might pinpoint a vurnerablity in the code.

All in all, good work on the gem, very much appreciated :)
