### ISSUE TITLE
Running rspec test failing with sprockets version =< 4

### ISSUE THREAD

**Issue by irondnb** [simukappu/activity_notification#117]
Hi, I'm trying to contribute and i've experienced error while running tests:

```
rspec spec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
ActivityNotification test parameters: AN_ORM=active_record(default) AN_TEST_DB=sqlite(default)

An error occurred while loading spec_helper.
Failure/Error: Rails.application.initialize!

Sprockets::Railtie::ManifestNeededError:
  Expected to find a manifest file in `app/assets/config/manifest.js`
  But did not, please create this file and use it to link any assets that need
  to be rendered by your app:

  Example:
    //= link_tree ../images
    //= link_directory ../javascripts .js
    //= link_directory ../stylesheets .css
  and restart your server
# /home/michal/.rvm/gems/ruby-2.5.1/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>'
# /home/michal/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4/lib/rails/initializable.rb:32:in `instance_exec'
# /home/michal/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4/lib/rails/initializable.rb:32:in `run'
# /home/michal/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4/lib/rails/initializable.rb:61:in `block in run_initializers'
# /home/michal/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4/lib/rails/initializable.rb:60:in `run_initializers'
# /home/michal/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4/lib/rails/application.rb:361:in `initialize!'
# ./spec/rails_app/config/environment.rb:8:in `<top (required)>'
# ./spec/spec_helper.rb:44:in `require'
# ./spec/spec_helper.rb:44:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00006 seconds (files took 1.1 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00006 seconds (files took 1.1 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


Coverage report generated for RSpec to /home/michal/activity_notification/coverage. 209 / 2390 LOC (8.74%) covered.
[Coveralls] Outside the CI environment, not sending data.
```
Following the issue here https://github.com/rails/sprockets-rails/issues/443 
I've fixed it with disabling version in gemfile

**Comment by simukappu** [comment]
I think this issue has been fixed at development branch by this commit. https://github.com/simukappu/activity_notification/commit/95d101b0a512a4209f09e634b95de70b2bbb0902

Can you confirm development branch?

**Comment by irondnb** [comment]
Ok my bad that i've started working from master branch. Its ok on development

I'm working on key uniqueness since uniqueness validation on db constraint and its raising an exception.

I've commented on development PR and i took slightly different approach:
https://github.com/irondnb/activity_notification/pull/2/files

Shall i create another issue for that?

**Comment by simukappu** [comment]
Thank you. I’ve checked your comments.
Can you create a PR to development branch?

**Comment by irondnb** [comment]
Sure I will, but i'm still working on it.
Looking for more versatile implementation for displaying/returning errors
