### ISSUE TITLE
App crashes due to syntax errors in swagger/notification_schema.rb

### ISSUE THREAD

**Issue by johannesengl** [simukappu/activity_notification#146]
### Steps to reproduce
Create new rails app with ruby 2.1.9 and rails 4.2.11.3. Add activity_notification to gem file
I created a test application for easy reproduction here: https://github.com/johannesengl/activity_notification_test

### Expected behavior
Should be able to start the rails server

### Actual behavior
The app crashes with the following error trace: 

```
johannesengl@192 activity_notification_test % rails s
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification.rb:71:in `require': /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:93: syntax error, unexpected ':', expecting => (SyntaxError)
              "test_default_param": "1"
                                   ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:94: syntax error, unexpected '}', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:142: syntax error, unexpected ':', expecting =>
                  "id": 1,
                       ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:143: syntax error, unexpected ':', expecting keyword_end
                  "email": "ichiro@example.com",
                          ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:143: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:144: syntax error, unexpected ':', expecting keyword_end
                  "name": "Ichiro",
                         ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:144: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:145: syntax error, unexpected ':', expecting keyword_end
                  "created_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:146: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "updated_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:147: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "provider": "email",
                             ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:147: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:148: syntax error, unexpected ':', expecting keyword_end
                  "uid": "",
                        ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:149: syntax error, unexpected ':', expecting keyword_end
                  "printable_type": "User",
                                   ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:149: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:150: syntax error, unexpected ':', expecting keyword_end
                  "printable_target_name": "Ichiro"
                                          ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:151: syntax error, unexpected '}', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:157: syntax error, unexpected ':', expecting =>
                  "id": 22,
                       ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:158: syntax error, unexpected ':', expecting keyword_end
                  "user_id": 2,
                            ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:159: syntax error, unexpected ':', expecting keyword_end
                  "article_id": 11,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:160: syntax error, unexpected ':', expecting keyword_end
                  "body": "This is the first Stephen's...
                         ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:160: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:161: syntax error, unexpected ':', expecting keyword_end
                  "created_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:162: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "updated_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:163: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "printable_type": "Comment"
                                   ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:164: syntax error, unexpected '}', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:171: syntax error, unexpected ':', expecting =>
                  "id": 11,
                       ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:172: syntax error, unexpected ':', expecting keyword_end
                  "user_id": 4,
                            ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:173: syntax error, unexpected ':', expecting keyword_end
                  "title": "Ichiro's great article",
                          ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:173: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:174: syntax error, unexpected ':', expecting keyword_end
                  "body": "This is Ichiro's great arti...
                         ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:174: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:175: syntax error, unexpected ':', expecting keyword_end
                  "created_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:176: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "updated_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:177: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "printable_type": "Article",
                                   ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:177: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:178: syntax error, unexpected ':', expecting keyword_end
...        "printable_group_name": "article \"Ichiro's great ar...
...                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:179: syntax error, unexpected '}', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:186: syntax error, unexpected ':', expecting =>
                  "id": 2,
                       ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:187: syntax error, unexpected ':', expecting keyword_end
                  "email": "stephen@example.com",
                          ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:187: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:188: syntax error, unexpected ':', expecting keyword_end
                  "name": "Stephen",
                         ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:188: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:189: syntax error, unexpected ':', expecting keyword_end
                  "created_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:190: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "updated_at": Time.current,
                               ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:191: syntax error, unexpected ':', expecting :: or '[' or '.'
                  "provider": "email",
                             ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:191: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:192: syntax error, unexpected ':', expecting keyword_end
                  "uid": "",
                        ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:193: syntax error, unexpected ':', expecting keyword_end
                  "printable_type": "User",
                                   ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:193: syntax error, unexpected ',', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:194: syntax error, unexpected ':', expecting keyword_end
                  "printable_notifier_name": "Stephen"
                                            ^
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:195: syntax error, unexpected '}', expecting keyword_end
/Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification/models/concerns/swagger/notification_schema.rb:209: syntax error, unexpected end-of-input, expecting keyword_end
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/activity_notification-2.1.3/lib/activity_notification.rb:71:in `<top (required)>'
	from /Users/johannesengl/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/bundler/runtime.rb:81:in `require'
	from /Users/johannesengl/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/johannesengl/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/bundler/runtime.rb:76:in `each'
	from /Users/johannesengl/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/bundler/runtime.rb:76:in `block in require'
	from /Users/johannesengl/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/bundler/runtime.rb:65:in `each'
	from /Users/johannesengl/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/bundler/runtime.rb:65:in `require'
	from /Users/johannesengl/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/bundler.rb:114:in `require'
	from /Users/johannesengl/Drive/Job/Aktuell/clunker-junker/activity_notification_test/config/application.rb:7:in `<top (required)>'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/railties-4.2.11.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/johannesengl/Drive/Job/Aktuell/clunker-junker/activity_notification_test/bin/rails:9:in `require'
	from /Users/johannesengl/Drive/Job/Aktuell/clunker-junker/activity_notification_test/bin/rails:9:in `<top (required)>'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/johannesengl/.rvm/gems/ruby-2.1.9/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/johannesengl/Drive/Job/Aktuell/clunker-junker/activity_notification_test/bin/spring:15:in `require'
	from /Users/johannesengl/Drive/Job/Aktuell/clunker-junker/activity_notification_test/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
johannesengl@192 activity_notification_test %
```

### System configuration
**activity_notification gem version**: 2.1.3
**Rails version**: 4.2.11.3
**ORM (ActiveRecord, Mongoid or Dynamoid)**: ActiveRecord

**Comment by simukappu** [comment]
We've just published as v2.1.4.
https://rubygems.org/gems/activity_notification/versions/2.1.4

Thank you!
