### ISSUE TITLE
ndefined method `printable_notifier_name' for #<User:0x00007fafdcd884f0> Did you mean? printable_target_name

### ISSUE THREAD

**Issue by guilhermegazzinelli** [simukappu/activity_notification#150]
### Steps to reproduce
Using API with devise. 

Routes:
```ruby
  scope :api do
    scope :v1 do
      # notify_to :users, api_mode: true
      notify_to :users, api_mode: true, with_devise: :users, devise_default_routes: true
    end
  end
```

Target config: 
```ruby 
acts_as_notifiable :users,
    targets: ->(action_plan, key) {
      ([action_plan.emitter.user] + User.find(action_plan.info["who"].map{|u| u["user_id"]}) + [User.first]).uniq
    },
    notifier:  ->(action_plan, key) {action_plan.emitter.user},
    email_allowed: true,
    send_later: false,
    notifiable_path: ->(action_plan, key) {"/one-action-plan#{action_plan.id}"},
    parameters: :subject_params(omited),
    # notifier_name: ->(action_plan) {action_plan.emitter.name}, 
    tracked: { only: [:create],  send_later: false }
```
What I've tried:

- ommiting notifier in notifiable setup
- override `notifier_name` in notifiable setup
- Added other parameters in setup. 
 

OBS.:  If I override controller just rendering JSON form current_user.notifications.as_json everything works - (Withouth `super` inside overriding controller.

### Expected behavior
Correct response from controller

### Actual behavior
**undefined method `printable_notifier_name'**
```ruby
NoMethodError (undefined method `printable_notifier_name' for #<User:0x00007fafdcd884f0>
Did you mean?  printable_target_name):

activemodel (5.2.4.1) lib/active_model/attribute_methods.rb:430:in `method_missing'
rolify (5.2.0) lib/rolify/role.rb:98:in `method_missing'
activemodel (5.2.4.1) lib/active_model/serialization.rb:139:in `block in serializable_hash'
activemodel (5.2.4.1) lib/active_model/serialization.rb:139:in `each'
activemodel (5.2.4.1) lib/active_model/serialization.rb:139:in `serializable_hash'
activerecord (5.2.4.1) lib/active_record/serialization.rb:19:in `serializable_hash'
devise (4.7.1) lib/devise/models/authenticatable.rb:115:in `serializable_hash'
activemodel (5.2.4.1) lib/active_model/serialization.rb:145:in `block in serializable_hash'
activemodel (5.2.4.1) lib/active_model/serialization.rb:187:in `block in serializable_add_includes'
activemodel (5.2.4.1) lib/active_model/serialization.rb:185:in `each'
activemodel (5.2.4.1) lib/active_model/serialization.rb:185:in `serializable_add_includes'
activemodel (5.2.4.1) lib/active_model/serialization.rb:141:in `serializable_hash'
activerecord (5.2.4.1) lib/active_record/serialization.rb:19:in `serializable_hash'
activemodel (5.2.4.1) lib/active_model/serializers/json.rb:100:in `as_json'
activesupport (5.2.4.1) lib/active_support/core_ext/object/json.rb:152:in `block in as_json'
activesupport (5.2.4.1) lib/active_support/core_ext/object/json.rb:152:in `map'
activesupport (5.2.4.1) lib/active_support/core_ext/object/json.rb:152:in `as_json'
activity_notification (2.1.3) app/controllers/activity_notification/notifications_api_controller.rb:32:in `index'
actionpack (5.2.4.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
activity_notification (2.1.3) lib/activity_notification/controllers/store_controller.rb:32:in `store_controller_for_activity_notification'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sentry-raven (3.1.1) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack-pjax (1.1.0) lib/rack/pjax.rb:12:in `call'
rack-attack (6.2.2) lib/rack/attack.rb:156:in `call'
rack-attack (6.2.2) lib/rack/attack.rb:163:in `call'
rack (2.0.8) lib/rack/session/abstract/id.rb:259:in `context'
rack (2.0.8) lib/rack/session/abstract/id.rb:253:in `call'
rack (2.0.8) lib/rack/method_override.rb:22:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
remotipart (1.4.4) lib/remotipart/middleware.rb:32:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.8) lib/rack/etag.rb:25:in `call'
rack (2.0.8) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.8) lib/rack/head.rb:12:in `call'
activerecord (5.2.4.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.8) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.8) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
sentry-raven (3.1.1) lib/raven/integrations/rack.rb:51:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread' 
```

### System configuration
**activity_notification gem version**: 2.1.3
**Rails version**: 6.0.6 and 5.2.2
**ORM (ActiveRecord, Mongoid or Dynamoid)**: ActiveRecord

**Comment by simukappu** [comment]
Hi @guilhermegazzinelli,

Define *acts_as_notifier* method in your *User* model, not only *acts_as_target*, like this:

```ruby
class User < ActiveRecord::Base
  acts_as_target ...

  acts_as_notifier printable_name: :name
end
```

Then, you can call *notify* with *User* model as notifiers:

```ruby
acts_as_notifiable :users,
    targets: ->(action_plan, key) {
      ([action_plan.emitter.user] + User.find(action_plan.info["who"].map{|u| u["user_id"]}) + [User.first]).uniq
    },
    notifier:  ->(action_plan, key) {action_plan.emitter.user},
    ...
```

Thanks!

**Comment by guilhermegazzinelli** [comment]
@simukappu Works perfectly!!!!!

Thanks!

**Comment by guilhermegazzinelli** [comment]
I just reopened to track this in documentation and see if I can give some help!
Thanks.
