### ISSUE TITLE
After adding gem to project get: Undefined method `protect_from_forgery' for ActivityNotification::SubscriptionsApiController:Class (NoMethodError)

### ISSUE THREAD

**Issue by 0vermore** [simukappu/activity_notification#169]
### Steps to reproduce

1. Add `gem 'activity_notification'` to Gemfile
2. Run `bundle install`
3. Start rails
4. Get error

### System configuration
**activity_notification gem version**: 2.2.3
**Rails version**: 6.1.4.4
**ORM ActiveRecord**: 6.1.4.4

### Log
```
api         | Traceback (most recent call last):
api         |   79: from bin/rails:2:in `<main>'
api         |   78: from bin/rails:2:in `load'
api         |   77: from /home/astral/api/bin/spring:7:in `<top (required)>'
api         |   76: from /home/astral/api/bin/spring:7:in `tap'
api         |   75: from /home/astral/api/bin/spring:10:in `block in <top (required)>'
api         |   74: from /home/astral/api/bin/spring:10:in `require'
api         |   73: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
api         |   72: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
api         |   71: from /usr/local/bundle/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
api         |   70: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
api         |   69: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
api         |   68: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
api         |   67: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
api         |   66: from /home/astral/api/bin/rails:5:in `<top (required)>'
api         |   65: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |   64: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |   63: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands.rb:18:in `<main>'
api         |   62: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/command.rb:48:in `invoke'
api         |   61: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/command/base.rb:69:in `perform'
api         |   60: from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
api         |   59: from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
api         |   58: from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
api         |   57: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:135:in `perform'
api         |   56: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:135:in `tap'
api         |   55: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:144:in `block in perform'
api         |   54: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:37:in `start'
api         |   53: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
api         |   52: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
api         |   51: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
api         |   50: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
api         |   49: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
api         |   48: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
api         |   47: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
api         |   46: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
api         |   45: from config.ru:5:in `block in <main>'
api         |   44: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
api         |   43: from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
api         |   42: from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
api         |   41: from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
api         |   40: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
api         |   39: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |   38: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |   37: from /home/astral/api/config/environment.rb:15:in `<main>'
api         |   36: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/application.rb:391:in `initialize!'
api         |   35: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/initializable.rb:60:in `run_initializers'
api         |   34: from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
api         |   33: from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
api         |   32: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
api         |   31: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
api         |   30: from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
api         |   29: from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
api         |   28: from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
api         |   27: from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
api         |   26: from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
api         |   25: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
api         |   24: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `run'
api         |   23: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `instance_exec'
api         |   22: from /usr/local/bundle/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
api         |   21: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:311:in `eager_load_all'
api         |   20: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:311:in `each'
api         |   19: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `eager_load'
api         |   18: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `synchronize'
api         |   17: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:226:in `block in eager_load'
api         |   16: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `ls'
api         |   15: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
api         |   14: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
api         |   13: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:231:in `block (2 levels) in eager_load'
api         |   12: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `cget'
api         |   11: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
api         |   10: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
api         |    9: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |    8: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |    7: from /usr/local/bundle/gems/activity_notification-2.2.3/app/controllers/activity_notification/subscriptions_api_with_devise_controller.rb:1:in `<main>'
api         |    6: from /usr/local/bundle/gems/activity_notification-2.2.3/app/controllers/activity_notification/subscriptions_api_with_devise_controller.rb:3:in `<module:ActivityNotification>'
api         |    5: from /usr/local/bundle/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
api         |    4: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |    3: from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api         |    2: from /usr/local/bundle/gems/activity_notification-2.2.3/app/controllers/activity_notification/subscriptions_api_controller.rb:1:in `<main>'
api         |    1: from /usr/local/bundle/gems/activity_notification-2.2.3/app/controllers/activity_notification/subscriptions_api_controller.rb:4:in `<module:ActivityNotification>'
api         | /usr/local/bundle/gems/activity_notification-2.2.3/app/controllers/activity_notification/subscriptions_api_controller.rb:8:in `<class:SubscriptionsApiController>': undefined method `protect_from_forgery' for ActivityNotification::SubscriptionsApiController:Class (NoMethodError)
api exited with code 1

```

**Comment by simukappu** [comment]
Can you create small test case?
