### ISSUE TITLE
find_or_create_subscriptions not working

### ISSUE THREAD

**Issue by johncadengo** [simukappu/activity_notification#77]
Here's an error I'm getting:

```
irb(main):012:0> user.find_or_create_subscription(key: "action_item.comment")
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "key"
LINE 1: ..." = $1 AND "subscriptions"."target_type" = $2 AND "key"."key...
                                                             ^
: SELECT  "subscriptions".* FROM "subscriptions" WHERE "subscriptions"."target_id" = $1 AND "subscriptions"."target_type" = $2 AND "key"."key" = $3 ORDER BY "subscriptions"."id" ASC LIMIT $4
```

The relevant line:

```
from /home/deploy/apps/app/shared/bundle/ruby/2.4.0/gems/activity_notification-1.4.4/lib/activity_notification/models/concerns/subscriber.rb:33:in `find_subscription'
	from /home/deploy/apps/app/shared/bundle/ruby/2.4.0/gems/activity_notification-1.4.4/lib/activity_notification/models/concerns/subscriber.rb:42:in `find_or_create_subscription'
```

**Comment by johncadengo** [comment]
Digging into the code, I was able to work on the `Subscription` model itself to unsubscribe. However, it would be nice to use this functionality and to understand what went wrong.

**Comment by simukappu** [comment]
Hi @johncadengo,

According to this query,
```
SELECT  "subscriptions".* FROM "subscriptions" WHERE "subscriptions"."target_id" = $1 AND "subscriptions"."target_type" = $2 AND "key"."key" = $3 ORDER BY "subscriptions"."id" ASC LIMIT $4
```
table name of `"key"."key"` seems to be wrong.

Can you try a simple argument to call `find_or_create_subscription` as
```
> user.find_or_create_subscription("action_item.comment")
```
instead of
```
> user.find_or_create_subscription(key: "action_item.comment")
```

Also see this API reference:
https://www.rubydoc.info/github/simukappu/activity_notification/ActivityNotification/Subscriber#find_or_create_subscription-instance_method

Thanks!

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
