### ISSUE TITLE
Bug in Subscriber Concern?

### ISSUE THREAD

**Issue by Mexxerio** [simukappu/activity_notification#80]
I've been trying to get subscriptions for optional targets to work. I have the option to automatically subscribe to notifications on false. But kept running into the following error:

```
ArgumentError: wrong number of arguments (given 0, expected 1..2)
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/subscription_api.rb:147:in `subscribing_to_optional_target?'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/models/concerns/subscriber.rb:175:in `evaluate_subscription'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/models/concerns/subscriber.rb:162:in `_subscribes_to_optional_target?'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/models/concerns/target.rb:466:in `subscribes_to_optional_target?'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:515:in `optional_target_subscribed?'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:357:in `block in publish_to_optional_targets'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:355:in `map'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:355:in `publish_to_optional_targets'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:225:in `notify_to'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/models/concerns/target.rb:318:in `notify_to'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:192:in `block in notify_all'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:192:in `map'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:192:in `notify_all'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/apis/notification_api.rb:169:in `notify'
api_1    | /usr/local/bundle/gems/activity_notification-1.5.0/lib/activity_notification/models/concerns/notifiable.rb:249:in `notify'
```

I tracked the issue down to the following line:
https://github.com/simukappu/activity_notification/blob/4217c3f62ffc3288bd85c2433561075e7d49e8a1/lib/activity_notification/models/concerns/subscriber.rb#L175

I think the issue here is that if `default` is false then `record.send(field)` gets called. But shouldn't it be `record.send(field, *args)` ?

**Comment by simukappu** [comment]
Hi @Mexxerio,

Thank you for your reporting! Maybe you are right. Can you give us Pull Request to development branch?

Regards

**Comment by simukappu** [comment]
I have added fix code from your issue in adobe referenced commit and release them as v1.5.1. I will close this issue.
Thank you for your contribution!
