### ISSUE TITLE
NoMethodError (undefined method 'notification_targets' for #<User:....> question 

### ISSUE THREAD

**Issue by RailsCod3rFuture** [simukappu/activity_notification#92]
I'm trying to use **acts_as_follower** with **activity_notification**, but it can't seem to locate the target for the follow. I tried a 3 different methods, but nothing seems to be working.

https://github.com/tcocca/acts_as_follower

```
NoMethodError (undefined method `notification_targets' for #<User:0x0000000012dd54e8>
Did you mean?  notification_keys):
  
app/controllers/users_controller.rb:34:in `follow'
Processing by ExceptionHandler::ExceptionsController#show as JS
  Parameters: {"id"=>"userone"}
Completed 500 Internal Server Error in 199ms (ActiveRecord: 0.0ms)
```

**users_controller.rb**
```

 def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
   # @user.notify :users, key: "user.followable"
    ActivityNotification::Notification.notify :users, @user, key: "user.follow"
    respond_to do |format|
      format.js {render :action => "follow"}
    end
  end
```

**follow.rb**

```
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower, polymorphic: true

  def activity_actor
    self.follower
  end
end
```

**user.rb**

```
class User < ApplicationRecord
  acts_as_target
  acts_as_followable
  acts_as_messageable
  acts_as_follower
end

```

If possible, can you show me how to group followers.

**Comment by simukappu** [comment]
Can you create simple case as test Rails application in *spec/rails_app*?

**Comment by RailsCod3rFuture** [comment]
I will try to recreate the issue with a test. I'll post back.

**Comment by RailsCod3rFuture** [comment]
I'm trying to test acts_as_follower and the gem itself is too outdated to get the correct results. Its stating that the methods for the gem itself, are not undefined...Even though, I included a reference to the base class for the gem. Can you attempt to add acts_as_follower to a test project to see if you can get the same results?  gem 'acts_as_follower', github: 'tcocca/acts_as_follower', branch: 'master' 

```
require './test/test_helper'

class ActsAsFollowerTest < ActiveSupport::TestCase
  test 'instance methods' do
    setup do
      @mikey = FactoryBot.create(:mikey)
    end
    assert @mikey.respond_to?(:following?)
    assert @mikey.respond_to?(:follow_count)
    assert @mikey.respond_to?(:follow)
    assert @mikey.respond_to?(:stop_following)
    assert @mikey.respond_to?(:follows_by_type)
    assert @mikey.respond_to?(:all_follows)
    @mikey = FactoryBot.create(:mikey)
    @megan = FactoryBot.create(:megan)
    @mikey.follow(@megan)
    @megan.follow(@mikey)

    # 'following'
    # "return following_status"
    assert_equal true, @mikey.following?(@megan)
    assert_equal true, @megan.following?(@mikey)

    #  "return follow_count" do
    assert_equal 1, @mikey.follow_count
    assert_equal 1, @megan.follow_count

  end


  test 'follow a friend' do
    setup do
      @megan.follow(@mikey)
    end

    assert_difference('Follow count', by: 1) {Follow.count}
    assert_difference('@megan.follow_count', by: 1) {@megan.follow_count}

    # "set the follower"
    assert_equal @megan, Follow.last.follower

    # "set the followable" do
    assert_equal @mikey, Follow.last.followable
  end

  test 'follow yourself' do
    setup do
      @megan.follow(@megan)
    end

    assert_no_difference('Follow count') {Follow.count}
    assert_no_difference('@megan.follow_count') {@megan.follow_count}

    # "not set the follower"
    assert_not_equal @megan, Follow.last.follower

    # "not set the followable"
    assert_not_equal @megan, Follow.last.followable
  end

  test 'stop_following' do
    setup do
      @mikey.stop_following(@megan)
    end

    assert_difference('Follow count', by: -1) {Follow.count}
    assert_difference('@mikey.follow_count', by: -1) {@mikey.follow_count}
  end

  test 'follows' do
    setup do
      # @band_follow = Follow.where("follower_id = ? and follower_type = 'User' and followable_id = ? and followable_type = 'Band'", @mikey.id, @oasis.id).first
      @user_follow = Follow.where("follower_id = ? and follower_type = 'User' and followable_id = ? and followable_type = 'User'", @mikey.id, @megan.id).first
    end

    test 'follows_by_type' do
      # "only return requested follows"
      assert_equal [@user_follow], @mikey.follows_by_type('User')
    end

    test 'all_follows' do
      # "return all follows"
      assert_equal 2, @mikey.all_follows.size
      # assert @mikey.all_follows.include?(@band_follow)
      assert @mikey.all_follows.include?(@user_follow)
      assert_equal [], @megan.all_follows

      # "accept AR options" do
      assert_equal 1, @mikey.all_follows(limit: 1).count
    end
  end

  test 'all_following' do
    # "return the actual follow records"
    assert_equal 2, @mikey.all_following.size
    assert @mikey.all_following.include?(@megan)
    assert_equal [], @megan.all_following

    # "accept AR limit option"
    assert_equal 1, @mikey.all_following(limit: 1).count
  end

  test 'following_by_type' do
    # "return only requested records"
    assert_equal [@megan], @mikey.following_by_type('User')
  end


  test 'method_missing' do
    # "call following_by_type"
    assert_equal [@megan], @mikey.following_users

    # "raise on no method"
    assert_raises (NoMethodError) {@mikey.foobar}
  end

  test 'respond_to?' do
    # "advertise that describe responds to following methods"
    assert @mikey.respond_to?(:following_users)
    assert @mikey.respond_to?(:following_users_count)

    # "return false when called with a nonexistent method" do
    assert !@mikey.respond_to?(:foobar)
  end

  test 'destroying follower' do
    setup do
      @megan.destroy
    end

    assert_difference('Follow.count', by: -1) {Follow.count}
    assert_difference('@mikey.follow_count', by: -1) {@mikey.follow_count}
  end

  test 'blocked by followable' do
    setup do
      @megan.block(@mikey)
    end

    # "return following_status"
    assert_equal false, @mikey.following?(@megan)

    # "return follow_count"
    assert_equal 1, @mikey.follow_count

    # "not return record of the blocked follows"
    assert_equal 1, @mikey.all_follows.size
    assert !@mikey.all_follows.include?(@user_follow)
    assert !@mikey.all_following.include?(@megan)
    assert_equal [], @mikey.following_by_type('User')
    assert_equal [], @mikey.follows_by_type('User')
    assert_equal [], @mikey.following_users
  end
end
```

**Comment by RailsCod3rFuture** [comment]
I tried adding the code below
users_controller.rb
```
def follow
 @user = User.find(params[:id])
    current_user.follow(@user)

    respond_to do |format|
      format.js { render action: 'follow' }
    end
    current_user.notify :users, @user
end
```
user.rb
acts_as_notifiable :users,
                     targets: -> (current_user, key) {[current_user.follow.last.followable]}

But, it doesn't work. I receive the error below.

 ```
(2.0ms)  SELECT COUNT(*) FROM "follows" WHERE "follows"."blocked" = $1 AND "follows"."follower_id" = $2 AND "follows"."follower_type" = $3 AND "follows"."followable_id" = $4 AND "follows"."followable_type" = $5  [["blocked", false], ["follower_id", 2], ["follower_type", "User"], ["followable_id", 5], ["followable_type", "User"]]
  Rendered users/_follow_user.html.erb (10.0ms)
  Rendered users/follow.js.erb (262.8ms)
Completed 500 Internal Server Error in 5538ms (Views: 5332.0ms | ActiveRecord: 18.0ms)


  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/models/user.rb:108:in `block in <class:User>'
app/controllers/users_controller.rb:35:in `follow'
Processing by ExceptionHandler::ExceptionsController#show as JS
  Parameters: {"id"=>"luv123"}
Completed 500 Internal Server Error in 222ms (ActiveRecord: 0.0ms)
```

**Comment by RailsCod3rFuture** [comment]
How do you create a manual notification to avoid having to use acts_as_follower methods within the notify block?

**Comment by RailsCod3rFuture** [comment]
Is it possible to simply notify through the user object after the follow is successful? Instead of using the follow class? If you know of any work arounds, I would be willing to try them.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
